In [1]:
import pandas as pd


In [2]:
messages = pd.read_csv('smsspamcollection.csv')

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### <span style="color:orange">Data Cleaning and Preprocessing</span>

In [4]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [5]:
word_net_lemmatizer = WordNetLemmatizer()

In [6]:
corpus = []

In [7]:
for i in range(0, len(messages) ):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i] )
    # review = review.lower()
    review = review.split()
    review = [word_net_lemmatizer.lemmatize(word, pos='v') for word in review
              if word not in set(stopwords.words('english') )]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
corpus

['Go jurong point crazy Available bugis n great world la e buffet Cine get amore wat',
 'Ok lar Joking wif u oni',
 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply',
 'U dun say early hor U c already say',
 'Nah I think go usf live around though',
 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv',
 'Even brother like speak They treat like aid patent',
 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friends Callertune',
 'WINNER As value network customer select receivea prize reward To claim call Claim code KL Valid hours',
 'Had mobile months U R entitle Update latest colour mobiles camera Free Call The Mobile Update Co FREE',
 'I gonna home soon want talk stuff anymore tonight k I cry enough today',
 'SIX chance win CASH From pound txt CSH send Cost p day days TsandCs apply Reply HL info',
 'URGENT You week FREE membership Prize Jackpot Txt word C

## <span style="color:orange">TF-IDF and N-grams</span>

### <span style="color:orange">TF-IDF alone.</span>

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
tf_idf = TfidfVectorizer(max_features=100)

independent_features = tf_idf.fit_transform(corpus).toarray()

In [11]:
independent_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
print(independent_features)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
import numpy as np

np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x) )

In [15]:
print(independent_features)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.379 0 0.407 0 0.584 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.591 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.454 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0.484 0 0 0 0 0 0 0 0 0.489 0 0 0 0 0 0 0 0 0 0.565 0 0 0 0 0]
 [0.511 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.622 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0.783 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0.391 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.414 0 0 ... 0 0.386 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.415 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [16]:
print(independent_features.shape)

(5572, 100)


___

### <span style="color:orange">TF-IDF with N-grams</span>

In [17]:
tf_idf_ngram = TfidfVectorizer(max_features=100, ngram_range=(2, 3) )

In [18]:
corpus2 = []

In [19]:
for i in range(0, len(messages) ):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i] )
    # review = review.lower()
    review = review.split()
    review = [word_net_lemmatizer.lemmatize(word, pos='v') for word in review
              if word not in set(stopwords.words('english') )]
    review = ' '.join(review)
    corpus2.append(review)

In [20]:
corpus2

['Go jurong point crazy Available bugis n great world la e buffet Cine get amore wat',
 'Ok lar Joking wif u oni',
 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply',
 'U dun say early hor U c already say',
 'Nah I think go usf live around though',
 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv',
 'Even brother like speak They treat like aid patent',
 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friends Callertune',
 'WINNER As value network customer select receivea prize reward To claim call Claim code KL Valid hours',
 'Had mobile months U R entitle Update latest colour mobiles camera Free Call The Mobile Update Co FREE',
 'I gonna home soon want talk stuff anymore tonight k I cry enough today',
 'SIX chance win CASH From pound txt CSH send Cost p day days TsandCs apply Reply HL info',
 'URGENT You week FREE membership Prize Jackpot Txt word C

In [21]:
independent_features2 = tf_idf_ngram.fit_transform(corpus2).toarray()

In [22]:
print(independent_features2)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [23]:
print(independent_features2.shape)

(5572, 100)


___

In [24]:
tf_idf.vocabulary_

{'go': 21,
 'great': 23,
 'get': 19,
 'wat': 88,
 'ok': 57,
 'free': 18,
 'win': 94,
 'text': 75,
 'txt': 84,
 'say': 66,
 'already': 0,
 'think': 77,
 'hey': 27,
 'week': 91,
 'back': 4,
 'like': 38,
 'still': 71,
 'send': 68,
 'prize': 63,
 'to': 80,
 'claim': 9,
 'call': 6,
 'mobile': 46,
 'the': 76,
 'home': 29,
 'want': 87,
 'today': 81,
 'cash': 8,
 'day': 12,
 'reply': 64,
 'you': 98,
 'no': 53,
 'www': 96,
 'right': 65,
 'take': 73,
 'time': 79,
 'have': 26,
 'message': 44,
 'oh': 56,
 'yes': 97,
 'make': 42,
 'way': 89,
 'feel': 16,
 'dont': 15,
 'miss': 45,
 'ur': 85,
 'try': 83,
 'so': 69,
 'da': 11,
 'lor': 39,
 'meet': 43,
 'just': 34,
 'this': 78,
 'know': 35,
 'are': 2,
 'leave': 37,
 'do': 14,
 'love': 40,
 'work': 95,
 'what': 93,
 'wait': 86,
 'but': 5,
 'tell': 74,
 'please': 61,
 'if': 32,
 'msg': 47,
 'see': 67,
 'how': 31,
 'pls': 62,
 'need': 50,
 'we': 90,
 'tomorrow': 82,
 'hope': 30,
 'well': 92,
 'lt': 41,
 'gt': 24,
 'ask': 3,
 'happy': 25,
 'sorry': 70,
 'g

In [25]:
tf_idf_ngram.vocabulary_

{'free entry': 31,
 'to claim': 81,
 'claim call': 15,
 'call claim': 2,
 'free call': 30,
 'chance win': 14,
 'txt word': 84,
 'let know': 51,
 'go home': 33,
 'we try': 93,
 'please call': 61,
 'lt gt': 56,
 'want go': 90,
 'like lt gt': 52,
 'sorry call': 74,
 'call later': 10,
 'sorry call later': 75,
 'ur award': 85,
 'how much': 46,
 'hi hi': 44,
 'come back': 20,
 'call customer': 3,
 'customer service': 22,
 'call customer service': 4,
 'po box': 63,
 'try contact': 82,
 'draw show': 27,
 'show prize': 72,
 'prize guaranteed': 66,
 'guaranteed call': 38,
 'valid hrs': 89,
 'we try contact': 94,
 'draw show prize': 28,
 'show prize guaranteed': 73,
 'prize guaranteed call': 67,
 'we go': 92,
 'select receive': 69,
 'private your': 64,
 'your account': 97,
 'account statement': 0,
 'call identifier': 5,
 'identifier code': 47,
 'code expires': 19,
 'private your account': 65,
 'your account statement': 98,
 'call identifier code': 6,
 'urgent your': 87,
 'your mobile': 99,
 'call

___